deployment:
  tasks:
  - export  DEPLOYPATH=/home/sbadvtmr/public_html
  - /bin/cp style.css $DEPLOYPATH
  - /bin/cp -r js $DEPLOYPATH
  - /bin/cp -r images $DEPLOYPATH
  - /bin/cp index.html $DEPLOYPATH
  - /bin/ls -la